language: python
services: docker

env:
  - BRANCH=master
  - BRANCH=4.0.2
  - BRANCH=3.8.1

script:
  - git clone https://github.com/compdatasci/octave-desktop.git master &&
    git clone -b $BRANCH https://github.com/compdatasci/octave-desktop.git daily &&
    docker build --tag compdatasci/octave-desktop:daily daily &&
    master/octave_desktop.py -d -n -t daily && docker stop $(docker ps -q)
  - docker images
