language: python
services: docker

env:
  - BRANCH=master
  - BRANCH=4.0.2

script:
  - git clone https://github.com/compdatasci/octave-desktop.git master &&
    git clone -b $BRANCH https://github.com/compdatasci/octave-desktop.git daily &&
    docker build --tag compdatasci/octave-desktop:daily daily &&
    master/octave-desktop.py -d -n -t daily && docker stop $(docker ps -q) &&
    master/octave-desktop.py -d -n -t daily && docker stop $(docker ps -q)
  - docker images
